---
extensions:
  health_check:

  pprof:
    endpoint: 0.0.0.0:1777

  zpages:
    endpoint: 0.0.0.0:55679
  
  ## Add when using gitprovider receiver with a private repository
  # bearertokenauth/github:
  #   token: ${env:GH_PAT}

receivers:
  otlp:
    protocols:
      grpc:
      http:

  # gitprovider:
  #   initial_delay: 1s
  #   collection_interval: 60s
  #   scrapers:
  #     github:
  #       github_org: ${env:GH_ORG}
  #       search_query: ${env:SEARCH_QUERY}
  #       metrics:
  #         git.repository.contributor.count:
  #           enabled: true
  #       ## You can specify a custom endpoint URL full list of client settings: https://github.com/open-telemetry/opentelemetry-collector/tree/main/config/confighttp#client-configuration
  #       #endpoint: "https://mygitlabenterprise.com"
  #       auth:
  #           authenticator: bearertokenauth/github

  prometheus:
    config:
      scrape_configs:
        - job_name: dev-otel-gateway-collector
          scrape_interval: 10s
          static_configs:
            - targets: [0.0.0.0:8888]

  k8s_cluster:
    collection_interval: 10s

processors:
  memory_limiter:
    check_interval: 1s
    limit_percentage: 75
    spike_limit_percentage: 15

  batch:
    send_batch_size: 100
    timeout: 10s

  resource/env:
    attributes:
      - key: environment.name
        value: dev
        action: upsert

  resource/logs:
    attributes:
      - key: loki.resource.labels
        action: insert
        value: service.name

  filter/duration_milliseconds_bucket:
    error_mode: ignore
    metrics:
      datapoint:
        - metric.name == "duration_milliseconds_bucket"

connectors:
  spanmetrics:

exporters:
  debug:
    verbosity: basic
    sampling_initial: 2
    sampling_thereafter: 500

  prometheusremotewrite:
    endpoint: http://grafana-lgtm.default.svc.cluster.local:9090/api/v1/write
    resource_to_telemetry_conversion:
      enabled: true

  otlphttp/otel:
    endpoint: http://grafana-lgtm.default.svc.cluster.local:4317/otlp

  loki:
    endpoint: http://grafana-lgtm.default.svc.cluster.local:3100/loki/api/v1/push

service:
  ## Add bearertokenauth/* if you want to use bearer token auth extensions
  extensions: [health_check, pprof, zpages]
  pipelines:
    metrics:
      ## Add gitprovider if you want to use gitprovider receiver
      receivers: [otlp, prometheus, spanmetrics]
      processors: [memory_limiter, filter/duration_milliseconds_bucket, batch, resource/env]
      exporters: [debug, prometheusremotewrite]

    logs:
      receivers: [otlp]
      processors: [memory_limiter, filter/duration_milliseconds_bucket, batch, resource/env, resource/logs]
      exporters: [debug, loki]

    traces:
      receivers: [otlp]
      processors: [memory_limiter, filter/duration_milliseconds_bucket, batch, resource/env, resource/logs]
      exporters: [debug, otlphttp/otel, spanmetrics]
