---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patches:
  - patch: |
      $patch: delete
      kind: Namespace
      metadata:
        name: ignored
    target:
      kind: Namespace

resources:
  - https://github.com/open-telemetry/opentelemetry-operator/releases/download/v0.92.1/opentelemetry-operator.yaml
