apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: grafana-lgtm
  name: grafana-lgtm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana-lgtm
  template:
    metadata:
      labels:
        app: grafana-lgtm
    spec:
      containers:
        - image: grafana/otel-lgtm:0.5.0
          imagePullPolicy: IfNotPresent
          name: grafana-lgtm
          ports:
            - containerPort: 3000
              name: grafana-ui
            - containerPort: 3100
              name: loki
            - containerPort: 4317
              name: traces-grpc
            - containerPort: 4318
              name: traces-http
            - containerPort: 9090
              name: prometheus
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
            requests:
              cpu: 200m
              memory: 64Mi
          volumeMounts:
            - name: provisioning1
              mountPath: /otel-lgtm/grafana-v10.4.1/conf/defaults.ini
              subPath: defaults.ini
            - name: provisioning1
              mountPath: /otel-lgtm/grafana-v10.4.1/conf/provisioning/dashboards/demo.yaml
              subPath: demo.yaml
            - name: provisioning1
              mountPath: /otel-lgtm/grafana-v10.4.1/conf/provisioning/dashboards/demo/engineering-effectiveness-metrics.json
              subPath: engineering-effectiveness-metrics.json
            - name: provisioning1
              mountPath: /otel-lgtm/grafana-v10.4.1/conf/provisioning/dashboards/demo/delivery-demo-dashboard.json
              subPath: delivery-demo-dashboard.json
            - name: provisioning1
              mountPath: /otel-lgtm/grafana-v10.4.1/conf/provisioning/dashboards/demo/demo-dashboard.json
              subPath: demo-dashboard.json
            - name: provisioning1
              mountPath: /otel-lgtm/grafana-v10.4.1/conf/provisioning/dashboards/demo/dora-demo-dashboard.json
              subPath: dora-demo-dashboard.json
            - name: provisioning2
              mountPath: /otel-lgtm/grafana-v10.4.1/conf/provisioning/dashboards/demo/opentelemetry-collector-data-flow.json
              subPath: opentelemetry-collector-data-flow.json
            - name: provisioning2
              mountPath: /otel-lgtm/grafana-v10.4.1/conf/provisioning/dashboards/demo/opentelemetry-collector.json
              subPath: opentelemetry-collector.json
            - name: provisioning2
              mountPath: /otel-lgtm/grafana-v10.4.1/conf/provisioning/dashboards/demo/spanmetrics-dashboard.json
              subPath: spanmetrics-dashboard.json
          
      volumes:
        - name: provisioning1
          configMap:
            name: provisioning1
        - name: provisioning2
          configMap:
            name: provisioning2
---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana-lgtm
  name: grafana-lgtm
spec:
  ports:
    - name: grafana-ui
      port: 3000
      targetPort: 3000
    - name: loki
      port: 3100
      targetPort: 3100
    - name: prometheus
      port: 9090
      targetPort: 9090
    - name: traces-grpc
      port: 4317
      targetPort: 4317
    - name: traces-http
      port: 4318
      targetPort: 4318
  selector:
    app: grafana-lgtm
  type: LoadBalancer


  
